server:
  port: 8070

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/students
    username: root
    password: root

mybatis:
  typeAliasesPackage: cn.xiangqiri.run.pojo
  mapperLocations: classpath:mappers/*.xml

  pagehelper:
    reasonable: true
    support-methods-arguments: true
    params: count=countSql


# pagehelper properties
#  pagehelper.offsetAsPageNum=true
#  pagehelper.rowBoundsWithCount=true
#  pagehelper.pageSizeZero=true
#  pagehelper.reasonable=false
#  pagehelper.params=pageNum=pageHelperStart;pageSize=pageHelperRows;
#  pagehelper.supportMethodsArguments=false



logging:
  level:
    com.tedu.mapper: debug
